### ISSUE TITLE
Full list of raw commands

### ISSUE THREAD

**Issue by mikz-t** [bremor/bonaire_myclimate#26]
Hi @bremor,

Would you happen to have a full list of the raw command parameters which can be used in a raw command sent to the controller?

Thanks,

**Comment by Knoxyv2** [comment]
Would also be interested in this.

Using the HomeKit module in HomeAssistant this integration works really well, however can only pass the system through as one big zone instead of passing both zones individually (outside the scope of this but the commands could solve this issue for users wanting to use that extra passthrough).

**Comment by bremor** [comment]
@Knoxyv2 I would love to help but I really do not understand much about homekit or what you are trying to do. Sorry!
